### ISSUE TITLE
Can't Set Up Integration: Unknown Error Occurred

### ISSUE THREAD

**Issue by MrAct1on** [fcastilloec/gkeep-list-sync#6] opened 2023-12-26 01:53 UTC
<img width="368" alt="Screenshot 2023-12-25 at 19 52 07" src="https://github.com/fcastilloec/gkeep-list-sync/assets/67850391/baac6b5d-acda-4331-be86-a395ebfbbd7d">

Followed instructions but I keep getting this error. Mind helping me figure this out?

**Comment by fcastilloec** [comment] 2023-12-27 17:51
This might be an issue previously reported. Somebody submitted a PR that could "fix" this. It's on my radar, but I don't have time to review it. In the meantime, you should check the logs to see if there's any additional information, and also check #2 

Duplicate of #2

**Closed by fcastilloec** 2023-12-27 17:51 UTC

**Comment by fcastilloec** [comment] 2023-12-28 16:36
Duplicate of #2
