### ISSUE TITLE
Login error: ('BadAuthentication', None)

### ISSUE THREAD

**Issue by viprapp** [fcastilloec/gkeep-list-sync#7] opened 2023-12-28 14:42 UTC
### Background
I was pleased to discover this integration which addresses the growing restrictions in Google's ecosystem, specifically enabling Google Nest speakers  and Home Assistant to work in tandem with Google Keep groceries lists. So thanks for making it happen @fcastilloec ! Unfortunately in my case I am not able to login and configure the Integration in my Home Assistant instance.

### Integration Details
- **Integration Version**: gkeep-list-sync v1.0.3 (HACS)

### Environment
- **Hardware**: Synology DiskStation DS720+
- **Software**: Home Assistant 2023.12.4 (Docker)

### Expected Behavior
1. Install the Integration via HACS.
2. Configure the Integration by logging into the GMail account using an email address and a Google App Password.
3. Complete additional Home Assistant configuration and utilize the Integration.

### Encountered Issue
During the login process,  an "Unknown error occurred" message is displayed in the UI. Additionally, the log produces "Login error: ('BadAuthentication', None)."

![SCR-20231228-noxs](https://github.com/fcastilloec/gkeep-list-sync/assets/25706638/526e34d4-b343-4403-9c0c-e6dbf4d08993)

### Steps to Reproduce
1. Install the Integration via HACS.
2. Attempt to log into the GMail account using an email address and a Google App Password.

Log:

```yaml
This error originated from a custom integration.

Logger: custom_components.gkeep_list_sync.config_flow
Source: custom_components/gkeep_list_sync/config_flow.py:64
Integration: Google Keep List Sync (documentation, issues)
First occurred: 00:41:10 (9 occurrences)
Last logged: 14:41:41

Login error: ('BadAuthentication', None)
```

The following log entry might be associated.
```python
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 00:41:10 (10 occurrences)
Last logged: 15:20:06

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 396, in _async_handle_step
    if result.get("preview") is not None:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by fcastilloec** [comment] 2023-12-28 16:35
Thanks for taking a look at this integration. I think you're bug has been reported already. There's a PR in the process that might help people get this configured, but I haven't had the time to review it.

**Comment by fcastilloec** [comment] 2023-12-28 16:36
Duplicate of #2

**Closed by fcastilloec** 2023-12-28 16:36 UTC

**Comment by viprapp** [comment] 2023-12-29 11:13
> Thanks for taking a look at this integration. I think you're bug has been reported already. There's a PR in the process that might help people get this configured, but I haven't had the time to review it.

Thanks for hinting to the other thread. I've noticed that there are several other closed threads about the same issue. It would be good to keep at least the first issue open so anyone landing on this project's issue page will see it and can engage directly to find temporary workarounds for them and avoid future duplicates on here.

**Comment by fcastilloec** [comment] 2023-12-29 16:12
Thanks for the suggestion, I pinned the issue so it's easier for people to see it.
It's just regular practice to search through the closed and opened issues to see if the problem has been reported before someone opens a new issue.
